In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
type(a)

numpy.ndarray

In [4]:
import numpy as np
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
c=np.array([1,2,3])
print(c)

[1 2 3]


In [7]:
len(b)

3

In [8]:
b.ndim

2

In [9]:
#get a shape an numpy array

b.shape

(3, 3)

In [13]:
#acessing /chnaging specific elements

z=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(z)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
z[0,4]=40
print(z)

[[ 1  2  3  4 40  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
#zeros and ones method

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((3,3),dtype='str')

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [19]:
varb=30
np.full((3,3),varb,dtype='float')

array([[30., 30., 30.],
       [30., 30., 30.],
       [30., 30., 30.]])

In [20]:
np.random.rand(4,4)

array([[0.87068184, 0.2700196 , 0.61022946, 0.85167631],
       [0.36115493, 0.58777072, 0.72235695, 0.65555594],
       [0.17643321, 0.85638154, 0.91390583, 0.33095021],
       [0.53414617, 0.57902409, 0.19321825, 0.22823173]])

In [21]:
np.random.randint(1,100,size=(3,3))

array([[60, 29, 44],
       [42, 91, 63],
       [47, 67, 57]])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.identity((5),dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
#extract all the first 3 rows of the last 5th column in a given numpy 2d array 'a'

a1 = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14],
    [15,16,17,18,19,20,21],
    [22,23,24,25,26,27,28]
])

result = a1[:3, -5]
print(result)

[ 3 10 17]


In [25]:
#given a positive no 'n' greater than 2 create a numpy array of size (n*n) with all zeros and ones such that the ones make a shape of plus

a2 = np.zeros((n, n), dtype=int)

mid = n // 2
a2[mid, :] = 1     
a2[:, mid] = 1     

print(a2)

[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


In [26]:
#diagonal should be one remaining all zeros
import numpy as np

n = 5   # n > 2

a = np.eye(n, dtype=int)

print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#airthmetic operation-maths and statstical

