In [ ]:
import numpy as np
a=np.array([[1,2,3]])
print(a)

[[1 2 3]]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([[1,2,3]],dtype=float)
print(a)

[[1. 2. 3.]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
len(b)

3

In [ ]:
c=np.array([1,2,3,4,5,6])
len(c)

6

In [ ]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(d)

numpy.ndarray

In [ ]:
np.ndim(d)

3

In [ ]:
d.ndim

3

In [ ]:
e=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(e)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [ ]:
np.ndim(e)

4

In [ ]:
e.ndim

4

In [ ]:
# Get a shape of a Numpy Array
e.shape

(1, 1, 3, 3)

In [ ]:
a.shape

(1, 3)

In [ ]:
# Accessing ? changing specific elements, rowa and columns
f=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(f)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
f[0,3]=40
print(f)

[[ 1  2  3 40  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
f[0,4]=250
print(f)

[[  1   2   3  40 250   6]
 [  7   8   9  10  11  12]]


In [ ]:
# Zeros & ones method in numpy
np.zeros((3,3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.full((3,3),7,dtype="float")

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [ ]:
np.random.randint(-1,0,size=(3,3))

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
np.identity((5),dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
g=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
g[:3,4:]

array([[ 5],
       [10],
       [15]])

In [ ]:
h=np.full((5,5),0,dtype="int")
print(h)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
h[2, :] = 1
h[:, 2] = 1

In [ ]:
print(h)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [ ]:
n=5
i=np.zeros((n,n),dtype="int")
print(i)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
i[n//2,:]=1
i[:,n//2]=1


In [ ]:
print(i)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [ ]:
np.identity((5),dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
j=np.array([[10,2,3]])

In [ ]:
j+2

array([[12,  4,  5]])

In [ ]:
j**2

array([[100,   4,   9]])

In [ ]:
j-2

array([[8, 0, 1]])

In [ ]:
j.min()

np.int64(2)

In [ ]:
np.min(j)

np.int64(2)

In [ ]:
j.max()

np.int64(10)

In [ ]:
np.max(j)

np.int64(10)

In [ ]:
k=np.array([[1,2,3],[4,5,6]])
print(k)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.min(k)

np.int64(1)

In [ ]:
np.max(k)

np.int64(6)