In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("C:/Users/MITS/Desktop/jagadeesh Data Analytics/python for data analytics/Churn_Modelling.csv")

In [7]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,NaN,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,NaN,NaN
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,NaN,NaN
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,NaN,NaN
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,NaN,NaN
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,NaN,NaN
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,NaN,NaN
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,NaN,NaN


In [12]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,NaN,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,NaN,NaN
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,NaN,NaN
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,NaN,NaN
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,NaN,NaN


In [15]:
new=df.sort_values('Age')
print(new)

      RowNumber  CustomerId      Surname  CreditScore Geography  Gender  Age  \
3512       3513    15657779       Boylan          806     Spain    Male   18   
1678       1679    15569178    Kharlamov          570    France  Female   18   
3517       3518    15757821      Burgess          771     Spain    Male   18   
9520       9521    15673180  Onyekaozulu          727   Germany  Female   18   
2021       2022    15795519     Vasiliev          716   Germany  Female   18   
...         ...         ...          ...          ...       ...     ...  ...   
3387       3388    15798024         Lori          537   Germany    Male   84   
3033       3034    15578006          Yao          787    France  Female   85   
2458       2459    15813303      Rearick          513     Spain    Male   88   
6759       6760    15660878        T'ien          705    France    Male   92   
6443       6444    15764927       Rogova          753    France    Male   92   

      Tenure    Balance  NumOfProducts 

In [14]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,NaN,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,NaN,NaN
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,NaN,NaN
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,NaN,NaN
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,NaN,NaN


In [16]:
#where clause using

df[df.Age>50]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,NaN,NaN
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,NaN,NaN
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,NaN,NaN
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,NaN,NaN
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,9937,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0,NaN,NaN
9939,9940,15808971,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0,NaN,NaN
9948,9949,15735078,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0,NaN,NaN
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0,NaN,NaN


In [3]:
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)

print(a)

np.ndim(a)


a[0,3]=50
print(a)

c=np.random.randint(1,10,size=(3,3))
print(c)
d=np.random.rand(1,10)
print(d)

d=np.random.randint(1,100,size=(5,5))


print(d)

ex=d[:3,-5:]
d.T

EX=np.ones((4,5),dtype=int)
EX1=np.zeros((5,5),dtype=int)

EX1[:5,2]=1
EX1[2,:5]=1
print(EX1)


import pandas as pd

roll=pd.Series(["manish","manish","hemanth","tharun","harsha"],index=[1,2,3,4,5])

print(roll)

roll.groupby(roll.values).count()

roll1=pd.DataFrame({
    "name":["manish","manish","hemanth","tharun","harsha"],
    "rollno":[1,2,3,4,5],
    "marks":[50,70,None,60,65]
})

print(roll1)

roll1.info()

roll1["marks"].isnull().sum()

roll1["marks"]=roll1["marks"].fillna(roll1["marks"].mean())

print(roll1)

roll1 = pd.DataFrame({
    "name":["manish","manish","hemanth","tharun","harsha"],
    "rollno":[1,2,3,4,5],
    "marks":[50,70,None,60,65]
})
roll1["marks"]=roll1["marks"].fillna(roll1["marks"].mean())



roll1.loc[(roll1["marks"]==70) & (roll1["name"]=="manish"),"name"]="manoj"

roll1["name"]=roll1["name"].str.replace("manish","baba")

roll1.groupby('name').count()

roll1

df1=pd.DataFrame({
    "name":["manish","manoj","hemanth","tharun","harsha"],
    "rollno":[1,2,3,4,5],
    "marks":[50,70,None,60,65]
})


df2=pd.DataFrame({
    "name":["manish","manoj","hemanth","tharun","harsha"],
    "rollno":[5,6,7,8,9],
    "marks":[90,45,44,60,45]
})
#

merge=pd.merge(df1,df2,on="name",how="inner")

print(merge)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[ 1.  2.  3. 50.]
 [ 5.  6.  7.  8.]]
[[6 2 2]
 [8 4 4]
 [1 2 1]]
[[0.30473174 0.35205384 0.02357862 0.88066784 0.95455619 0.67952952
  0.21137528 0.4349273  0.08805588 0.41842372]]
[[10  3 69 38 58]
 [64 29 95 73 62]
 [62 41 38 36 91]
 [86 26 92 59 48]
 [35 64 39 75 67]]
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
1     manish
2     manish
3    hemanth
4     tharun
5     harsha
dtype: object
      name  rollno  marks
0   manish       1   50.0
1   manish       2   70.0
2  hemanth       3    NaN
3   tharun       4   60.0
4   harsha       5   65.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   rollno  5 non-null      int64  
 2   marks   4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
      name  rollno  marks
0   manish      

In [8]:
#loc and iloc

df.loc[0]

RowNumber                  1
CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Unnamed: 14              NaN
Unnamed: 15              NaN
Name: 0, dtype: object

In [9]:
df.iloc[0]

RowNumber                  1
CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Unnamed: 14              NaN
Unnamed: 15              NaN
Name: 0, dtype: object

In [10]:
df.loc[1]

RowNumber                  2
CustomerId          15647311
Surname                 Hill
CreditScore              608
Geography              Spain
Gender                Female
Age                       41
Tenure                     1
Balance             83807.86
NumOfProducts              1
HasCrCard                  0
IsActiveMember             1
EstimatedSalary    112542.58
Exited                     0
Unnamed: 14              NaN
Unnamed: 15              NaN
Name: 1, dtype: object

In [11]:
df.iloc[2]

RowNumber                  3
CustomerId          15619304
Surname                 Onio
CreditScore              502
Geography             France
Gender                Female
Age                       42
Tenure                     8
Balance             159660.8
NumOfProducts              3
HasCrCard                  1
IsActiveMember             0
EstimatedSalary    113931.57
Exited                     1
Unnamed: 14              NaN
Unnamed: 15              NaN
Name: 2, dtype: object

In [12]:
df.iloc[0:1]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.0,1,1,1,101348.88,1,NaN,NaN


In [13]:
df.loc[1:2]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,NaN,NaN
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,NaN,NaN
